### ISSUE TITLE
Why are you using pooling layers?

### ISSUE THREAD

**Issue by m4r1vs** [Sentdex/pygta5#66]
I'm really new to all this AI and NN stuff, so please correct me if I'm wrong.
After reading some papers about the DeepMind Atari agent, I learned, that they removed all pooling layers from their convolutional neural nets. Pooling layers are there to make the net nonsensitive to positions of objects, but since that's also very important, shouldn't we remove all pooling layers from the model?

**Comment by lenixlobo** [comment]
Pooling layers are used to select the most optimal pixel/branch of the image.It then becomes a part of the memory,hence when the pixel is repeated/similar the NN selects the optimal action to be taken from the knowledge gained through the previous pixel.As the Memory and pixels and repeated the agent learns the most optimal solution for maximum reward.

What DeepMind did was adapt an Optimized algorithm called AAAC,in which asynchronous actors are able to select Multiple options / actions and adapt the optimal one,hence for every frame you have multiple agents who learn from each other and hence adapt more efficiently.Hence,there was no need for a detailed Pooling layer since the actors are able to adapt through the entire frame.

Hope this clears it out. @m4r1vs

**Comment by racinmat** [comment]
"Pooling layers are there to make the net nonsensitive to positions of objects" Remenber that pooling layers usually don't pool from all pixels, but from some small matrix, so e.g. if there is 4x4 pooling layer, every neuron here is selecting most importnat neuron from previous layer only from 16 neurons.

[This article](http://www.ais.uni-bonn.de/papers/icann2010_maxpool.pdf) from 2010 proposes pooling layers and demonstrates that they outperform other methods.

In NN, all layers are mostly used because there is a paper which shows significant improvement when using that type of layer.
